### ISSUE TITLE
dodac zombie

### ISSUE THREAD

**Issue by Wik668** [Wik668/PROJEKT#13]

**Comment by Wik668** [comment]
9f23f2aa285c7710f6ebfb7bd33a342b80b229a6
b3fdc70ff12eddadca73f27f8367533d087eefad
47fbc0677b82016a2ea32cb1350c9e0adc092e25

**Comment by JakubChrusciel** [comment]
![Walk_Zombie](https://github.com/Wik668/PROJEKT/assets/163772348/d44472fb-d462-4b8e-b8da-c49328a3da29)
