### ISSUE TITLE
dodać ninja

### ISSUE THREAD

**Issue by Wik668** [Wik668/PROJEKT#15]

**Comment by Wik668** [comment]
889e4c47831aa54a1ab9a84259d3c84e3e6f00d7
863c2ad319fcc5afc29b4a5b6fc1403bf030c746
30ba802e20da63b1c90b0bb888d6768578bfa0d2
502b60db34ac47eca2bf427488febe31927e7350

**Comment by JakubChrusciel** [comment]
![enemy2](https://github.com/Wik668/PROJEKT/assets/163772348/dbbeb12b-0cc1-4f47-a035-cb36d1f9393c)
