### ISSUE TITLE
Animacja śmierci Bossa todo

### ISSUE THREAD

**Issue by JakubChrusciel** [Wik668/PROJEKT#32]

**Comment by Wik668** [comment]
64a404526c786f7b65133d97cb4fbe45445fbc34
d5f8b735d2de68d2aa83943d644dbba73685ebc3
162091edb4785ac564a0353f14e0cb8b7022e626
9339dce3cc490c800a4f9adc1bed45b5c53bb01c

**Comment by Wik668** [comment]
bdebedfe9a76c1432e99560957ca565a511f1e1a
