### ISSUE TITLE
dodac jakąś muzyke w endgame menu

### ISSUE THREAD

**Issue by JakubChrusciel** [Wik668/PROJEKT#35]

**Comment by Wik668** [comment]
f369ec0dedfc0b636fe738d2542111dbd05a2051
d5f8b735d2de68d2aa83943d644dbba73685ebc3

**Comment by Wik668** [comment]
d5f8b735d2de68d2aa83943d644dbba73685ebc3
4047cb2a1aaa314d1938ce1b5458afa011876f3f
