### ISSUE TITLE
Do oceny

### ISSUE THREAD

**Issue by Wik668** [Wik668/PROJEKT#42]

**Comment by JOtworowski** [comment]
Gra wykonana bardzo dobrze. Github prowadzony zgodnie z wymaganiami, w projekcie wykorzystano dziedziczenie oraz polimorfizm i alokacje pamięci. Plik .exe odpala się bez problemów. Gameplay jest wykonany starannie, drobny problem jaki zauważyłem dotyczył bossa i jego wystawania poza ekran. Poza tym uważam że przyciski w menu nie są wystarczająco czytelne (można by dobrać nieco inny kolor i powinno być lepiej). Testując grę jeden raz zdarzyło się że ninja zespawnował się niemalże na bohaterze co sprawilo że na samym początku straciłem nieco zbyt dużo hp. Jednak chcę podkreślić że mimio tych drobnych mankamentów gra jest bardzo przyjemna, powerupy są dobrze zbalansowane, animacje są płynne. Plusem jest także to że mimo wielu przeciwników na ekranie nie doświadczyłem żadnych spadków płynności.

Podsumowując projekt oceniam na 92,5 %, ponieważ pomimo że znalazłem drobne mankamenty gra jest bardzo dobra biorąc pod uwagę w jak krótkim czasie powstała.
