### ISSUE TITLE
Postać

### ISSUE THREAD

**Issue by JakubChrusciel** [Wik668/PROJEKT#5]
konfiguracja wycinków sprite'a postaci

**Comment by Wik668** [comment]
Commit b85d6bbb21e7cd1691c60538bd9c3c1e2371f474
Commit b75278e80a00101559ffa5c66e927b290304f39d
Commit 90c596136e05ab7931101c1c5cc23d6c13572ac0
Commit 90c596136e05ab7931101c1c5cc23d6c13572ac0
Commit a83b283c6f9b4a631b3d05f337ca919d511d1424

**Comment by JakubChrusciel** [comment]
![Walk](https://github.com/Wik668/PROJEKT/assets/163772348/bf1cc2e9-f1a7-45f0-9824-3fad7a6a84f8)
